Repository moonbitlang/core, pull requests merged in 2024-08, with the labels that each got.

#829 add [ToJson] trait & [to_json] method for builtin types
  builtin/builtin.mbti
  builtin/json.mbt
  json/to_json_test.mbt
Labels: APPROVED

#855 quickcheck utils
  quickcheck/arbitrary.mbt
  quickcheck/arbitrary.mbti
  quickcheck/moon.pkg.json
  quickcheck/quickcheck.mbti
  random/splitmix/moon.pkg.json
  random/splitmix/random.mbt
  random/splitmix/splitmix.mbti
  tuple/moon.pkg.json
  tuple/tuple.mbti
  tuple/tuple_arbitrary.mbt
Labels: review-needed

#834 add flat_map to list, deprecate concat_map
  immut/list/list.mbt
  immut/list/list.mbti
  immut/list/list_test.mbt
Labels: consistency review

#935 feat: change radix of bigint to 2^32
  builtin/bigint.mbt
  builtin/bigint_wbtest.mbt
Labels: APPROVED
